### ISSUE TITLE
Issues with paths that contain spaces

### ISSUE THREAD

**Issue by pf1gura** [sebescudie/GoConemu#1]
The plugin sends wrong path to ConEmu when there is a space in it.

![ConEmu64_D9OFY2reml](https://user-images.githubusercontent.com/41795518/57183809-8b312a80-6eb2-11e9-9602-f6667b398bae.png)

**Comment by sebescudie** [comment]
Hey,

Thanks for submitting this issue, I'll try to take a look at it tomorrow.

**Comment by sebescudie** [comment]
Hey @pf1gura, could you test and report if the master branch is OK for you ? Thanks.

**Comment by pf1gura** [comment]
@sebescudie seems to be working fine now. Thanks for taking care of it.

**Comment by sebescudie** [comment]
Great, thanks for reporting!
